apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronfortodoapp
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 120
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: ikulyk404/busyboxplus:curl
            resources:
              requests:
                cpu: "50m"
                memory: "64Mi"
            command:
              - "sh"
              - "-c"
              - "curl http://todoapp-service.todoapp.svc.cluster.local:80/api/health"
          restartPolicy: Never
